import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/brand/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center h-screen">
        <h1>Hello world!</h1>
      </div>
    </div>
  );
};

export default Home;
